MAGIC_NONE = 0x0000000  # No flags
MAGIC_DEBUG = 0x0000001  # Turn on debugging
MAGIC_SYMLINK = 0x0000002  # Follow symlinks
MAGIC_COMPRESS = 0x0000004  # Check inside compressed files
MAGIC_DEVICES = 0x0000008  # Look at the contents of devices
MAGIC_MIME_TYPE = 0x0000010  # Return a mime string
MAGIC_CONTINUE = 0x0000020  # Return all matches
MAGIC_CHECK = 0x0000040  # Print warnings to stderr
MAGIC_PRESERVE_ATIME = 0x0000080  # Restore access time on exit
MAGIC_RAW = 0x0000100  # Don't translate unprintable chars
MAGIC_ERROR = 0x0000200  # Handle ENOENT etc as real errors
MAGIC_MIME_ENCODING = 0x0000400  # Return the MIME encoding
MAGIC_APPLE = 0x0000800  # Return the Apple creator/type
MAGIC_MIME = MAGIC_MIME_TYPE | MAGIC_MIME_ENCODING  # Return a mime string
MAGIC_EXTENSION = 0x1000000  # Return a /-separated list of extensions
MAGIC_COMPRESS_TRANSP = 0x2000000  # Check inside compressed files, but not report compression
MAGIC_NODESC = MAGIC_EXTENSION | MAGIC_MIME | MAGIC_APPLE

MAGIC_NO_CHECK_COMPRESS = 0x0001000  # Don't check for compressed files
MAGIC_NO_CHECK_TAR = 0x0002000  # Don't check for tar files
MAGIC_NO_CHECK_SOFT = 0x0004000  # Don't check magic entries
MAGIC_NO_CHECK_APPTYPE = 0x0008000  # Don't check application type
MAGIC_NO_CHECK_ELF = 0x0010000  # Don't check for elf details
MAGIC_NO_CHECK_TEXT = 0x0020000  # Don't check for text files
MAGIC_NO_CHECK_CDF = 0x0040000  # Don't check for cdf files
MAGIC_NO_CHECK_CSV = 0x0080000  # Don't check for CSV files
MAGIC_NO_CHECK_TOKENS = 0x0100000  # Don't check ascii/tokens
MAGIC_NO_CHECK_ENCODING = 0x0200000  # Don't check text encodings
MAGIC_NO_CHECK_JSON = 0x0400000  # Don't check for JSON files

MAGIC_PARAM_INDIR_MAX = 0  # Recursion limit for indirect magic
MAGIC_PARAM_NAME_MAX = 1  # Use count limit for name/use magic
MAGIC_PARAM_ELF_PHNUM_MAX = 2  # Max ELF notes processed
MAGIC_PARAM_ELF_SHNUM_MAX = 3  # Max ELF program sections processed
MAGIC_PARAM_ELF_NOTES_MAX = 4  # # Max ELF sections processed
MAGIC_PARAM_REGEX_MAX = 5  # Length limit for regex searches
MAGIC_PARAM_BYTES_MAX = 6  # Max number of bytes to read from file
MAGIC_PARAM_ENCODING_MAX = 7
